### ISSUE TITLE
are you logging all the timestamped data?

### ISSUE THREAD

**Issue by mofosyne** [jhon/robintracker#10]
It would be interesting if you can release the dataset after all of this for some historical plotting

**Comment by cyberbalsa** [comment]
its based around my old system, from what I understand it is being recorded, every single entry

**Comment by jhon** [comment]
I am. You can see some of that data through the pedigree.json entry point right now (in term of room formation / end).

I intend to release the SQL dumps once robin shuts down.

**Comment by mofosyne** [comment]
I think https://www.reddit.com/user/GarageguyEVe will be interested in the
data.

**Comment by jhon** [comment]
Leaving this open since I still have things to meet this issue. I hope to have the data up by mid-day PDT tomorrow. If not, hassle me :)

**Comment by jhon** [comment]
If you have any issues with this data, please submit a new issue.

The tier and pedigree information is available here: https://monstrouspeace.com/robintracker/dump/pedigree.json

Room Data: https://monstrouspeace.com/robintracker/dump/rooms.sql.gz

Tracking Beacon Data: https://monstrouspeace.com/robintracker/dump/track_storage.sql.gz
