### ISSUE TITLE
chatroom growth prediction?

### ISSUE THREAD

**Issue by ghost** [jhon/robintracker#6]
Hi.  So I'm no coder/scripter so bear with me.
Oh, and this is a feature request FYI.

So if you have the timestamp data of all the groups as they've been merged (and possibly destroyed as well), then shouldn't you be able to math out the average time it takes for a group of a certain tier to form?

Basically, what's the average ETA it takes to make say, a Tier 8 chatroom?
What about a Tier 9 chatroom?
How many Tier 7 chatrooms don't ever make it to Tier 8?
etc.

I think these calculations will massively help the higher-tier chats, in getting at least a generalized estimate for how long it will be until their next merge, and how long many merges we can realistically expect before /robin ends.

Am I making any sense here?  Let me know if I'm not :)

Thanks,
/u/kitefrog

**Comment by jhon** [comment]
This is a great idea! I may take a look at this at some point. If someone is interested in pulling this data to make a thing generally, the JSON data is available for all the pedigree information is available here: https://monstrouspeace.com/robintracker/dump/pedigree.json

**Comment by ghost** [comment]
@jhon Does that json data update periodically?

**Comment by jhon** [comment]
@veganzombeh Yes it does. However, being that it is a several MB json file, I wouldn't actually attach it to a webpage :p If you provide a script that uses that to calculate tier predictions, it should be easy enough to integrate it in a way that uses the database instead of that file.

**Comment by ghost** [comment]
@jhon I've lost the script I wrote, but you can iterate over each room and keep a running total of 2^tier, so something like 

```
$total = 0;
$target_tier = 17;

foreach($room_array as $tier) {
    $total = $total + $tier;
    echo (($total/(2^$target_tier))*100);
}
```

where $room_array is an array containing the tier of each room

`$total/(2^target_tier))*100` gives us a rough percentage indicating how close we are to the specified tier. You could then check periodically and estimate a time for the merge based on how fast it's increasing.

I'm going to sleep now, but if we haven't hit T17 by morning and you haven't implemented anything like this yourself I'll attempt submit a PR.

**Comment by jhon** [comment]
I added something similar to that today:
New T8s Needed For T17  32  This may be inaccurate during merges.

Is that the sort of thing you were looking for?

**Comment by jhon** [comment]
Closing since Robin is dead D:
