### ISSUE TITLE
t9s don't seem to be merging. 

### ISSUE THREAD

**Issue by theolas** [jhon/robintracker#8]
Not sure which party is responsible for the error.
Screenie: http://puu.sh/o83vV/f52ef576e7.png

**Comment by jhon** [comment]
They didn't merge because SmIAroNeCo was actually T10. Leaving this open so I can look into why it miscalculated it initially.

https://monstrouspeace.com/robintracker/graph.php?guid=b972799e-fbe2-11e5-98e1-0e31fc1b0d95

**Comment by jhon** [comment]
Closing since Robin is dead D:
