### ISSUE TITLE
Suggestion for dealing with higher traffic

### ISSUE THREAD

**Issue by steverobbins** [jhon/robintracker#9]
Each request is causing `index.php` to execute, but it really only needs to run once for all the hits that second.

I.e.

```
php index.php > index.html
```

Will save the output to `index.html` which uses less resources for each request.

You could set a cron to regenerate the cached html, but updating once a minute might not be frequent enough.

Something like 

```
nohup watch -n 5 "php index.php > index.html" &
```

Would create a daemon-ish process that regenerates `index.html` every 5 seconds.

You can use `htop`/`ps aux | grep php`/`kill` to stop the daemon.

**Comment by jhon** [comment]
Implemented this via cron/genIndex.sh

Saw a significant reduction in CPU usage by php.cgi as a result. Thanks for the suggestion!
